### ISSUE TITLE
when clicking on a task far down with mouse, the animation take a long time before task is selected

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#10]
Animation should be faster and disabled to select a task far down

**Comment by fuchsmich** [comment]
How do you think about animations in general?
I'm not too keen about them. The ones activated are the default 
animations, thats why they are there.

qml provides numbers of ways to implement animations. but I didn't do 
much with them yet.

so if you want I can look, how to make them prettier, or if you don't 
like them, I'd rather turn them off.


Am 18.04.2017 um 10:01 schrieb oroulet:

**Comment by oroulet** [comment]
Turn then of. My opinion is that animations should only be enabled when
they help users understand what is happening

**Comment by fuchsmich** [comment]
I set duartion of the animation to 0 as workaround. I will need some more investigation on how to handle animations correctly.
