### ISSUE TITLE
Tasks not correctly displayed on windows

### ISSUE THREAD

**Issue by topas-rec** [QTodoTxt/QTodoTxt2#121]
When opening a larger file with about 50 tasks on windows using the installer or portable version some tasks are not shown and the priority of tasks is not shown correctly. (All tasks somehow have only priority A or B though there are tasks in the to do.txt file that have other priorities)

**Comment by topas-rec** [comment]
Correction: Even with a small (the example) file the content of the task list gets wrong.
To reproduce this change the filtered list on the left until tasks are shown in the task list that are wrong according to the selected filter.

Once again: This issue is Windows only! (Tested with Linux Mint 18.3 and works fine)

@oroulet: Have you seen something like this during initial development?


<img width="672" alt="qtodotxt2_issue_121" src="https://user-images.githubusercontent.com/20391449/53693154-a7262c00-3d9c-11e9-9bd6-22eb54848082.PNG">

**Comment by topas-rec** [comment]
The filter tasks function always produces the correct output. (Correct tasks) It seems only the display in the table view is not correct.

**Comment by alvcap** [comment]
I have played a bit with the code. Commenting out the references to TaskLine.qml in TaskListTableView.qml, makes the table display the tasks correctly. Looks like something in TaskLine is resorting the tasks incorrectly.. 

```
  TableViewColumn {
        role: "html"
        /*delegate: TaskLine {

            current: (styleData.selected && listView.currentRow === styleData.row)
            onCurrentChanged: {
                if (current) listView.currentItem = this
            }
            onHeightChanged: {
                listView.rowHeightChanged(styleData.row, height)
            }
            onHoveredChanged: {
                listView.rowHoveredChanged(styleData.row, hovered)
            }
            Component.onCompleted: task = taskList[styleData.row]
        }*/
    }
```

**Comment by topas-rec** [comment]
Duplicate of #101
