### ISSUE TITLE
completer broken on my system. No error message

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#13]
git bisect bad
9d46f8887c0ac4ce8518d3c73bfa051177cf1dc6 is the first bad commit
commit 9d46f8887c0ac4ce8518d3c73bfa051177cf1dc6
Author: Michael Fuchs <michfu@gmx.at>
Date:   Sat Apr 22 00:25:46 2017 +0200

    more elegance to completer

:040000 040000 768beaff55bb63e1c83a338e832d50b63a8a75f6 fe107a9876619b0e3534df46f9e87c133d5bc568 M	qtodotxt

**Comment by fuchsmich** [comment]
Sorry, did i mess up something? What do I have to do?

Am 24.04.2017 um 10:12 schrieb oroulet:

**Comment by oroulet** [comment]
No Idea. No popup comes up... probably a difference between my version of
qt and yours...... I am trying to put some log to understand where the
error happens...

**Comment by oroulet** [comment]
even the onActiveFocusChanged signal in CompletionPopup.qml is not called....

**Comment by oroulet** [comment]
sorry onActiveFocusChanged is called when exiting editor, but not when entering it....

**Comment by oroulet** [comment]
that is probably where the problem is

**Comment by fuchsmich** [comment]
I have some ideas for improvement.

Am 24.04.2017 um 10:24 schrieb oroulet:

**Comment by fuchsmich** [comment]
I uploaded some changes.
If it works for you: Could you please check, when this line:

https://github.com/QTodoTxt/QTodoTxt2/blob/qml/qtodotxt/qml/TaskLine.qml#L74

is removed, does the behaviour of the popup change on your system?

**Comment by oroulet** [comment]
works now! with and without that 'force focus' line

**Comment by oroulet** [comment]
btw when starting editing, I think we should move cursor to end of line, not beginning

**Comment by fuchsmich** [comment]
ok, did it.

Am 24.04.2017 um 15:22 schrieb oroulet:
