### ISSUE TITLE
text not saved if window loses focus while editing

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#14]
This is an issue in qml

**Comment by fuchsmich** [comment]
How do we want to solve this?
Should the editor stay open, when the window goes to background (would 
probably be usefull when copy&pasting from other applications) or do you 
want to save the current text?

Have to think about how to tell the editor the difference between losing 
focus inside or outside the app...

Am 26.04.2017 um 13:05 schrieb oroulet:

**Comment by oroulet** [comment]
Saving is safer I suppose

**Comment by fuchsmich** [comment]
is this solved?

**Comment by oroulet** [comment]
kind of. I remember seeing unintuitive behaviour, I need to test more. But currently there is something quite strange. If create a new task, I see that the onInputAccepted is called, it should not. it generates a new filtering and make the program in some situations. Can you have a look? I could not understand what is happening. onInputAccepted should only be called when editing is finished....

**Comment by oroulet** [comment]
and escape should cancel changes, I think this is broken currently..

**Comment by fuchsmich** [comment]
ok, i will have a look.

Am 11.05.2017 um 21:07 schrieb oroulet:

**Comment by oroulet** [comment]
great!

**Comment by oroulet** [comment]
If you select a filter (Priority/A for example) then click on "new task" I get a crash , every second time. with a wanring about corrupt double list. I used git bisect and the suspect seems to be commit
5b9991ddb54209fc91a1288b1df054e66314f2b is the first bad commit
commit 45b9991ddb54209fc91a1288b1df054e66314f2b

**Comment by oroulet** [comment]
do you reproduce the crash and have any idea where the issue is???

**Comment by fuchsmich** [comment]
Yes, seems like my logic for saving when losing focus is incomplete. Have to rethink this.

**Comment by fuchsmich** [comment]
I commented out the two lines, which should detect the loss of focus of the app. This shoult prevent the crash.
...I'm a bit busy these days, sorry.

**Comment by oroulet** [comment]
I commited a fix that seems to work...

**Comment by protist** [comment]
What was actually fixed here? Was it just the crash? For me, if the window loses focus, I still lose text. i.e.

1. Create a new item
2. Type text
3. Alt-tab to look at something else
4. Come back to QTodoTxt2

And all the text of this item is now missing.
