### ISSUE TITLE
Seg Fault when running

### ISSUE THREAD

**Issue by PerrinWaldock** [QTodoTxt/QTodoTxt2#144]
I'm running Linux Mint 20. I pulled from the repository and tried running both qtodotxt as an executable and "python qtodotxt.pyw". Both result in "Segmentation fault (core dumped)"

**Comment by paper42** [comment]
Hi, can you try to clone the master:
```
%: git clone https://github.com/QTodoTxt/QTodoTxt2/
%: cd QTodoTxt2
```
and run it:
```
%: bin/qtodotxt2
```
then please post the whole output

are you sure you are using qtodotxt**2**?

**Comment by PerrinWaldock** [comment]
I recloned the master and it seems to work now (using qtodotxt; qtodotxt2 doesn't exist in bin/). The only concerning messages that came up were 
```filteredTasks about to change in python``` 
and when I closed the application, it said 
```
Must construct a QGuiApplication first.
Segmentation fault (core dumped)
```
