### ISSUE TITLE
FilterView Layout

### ISSUE THREAD

**Issue by fuchsmich** [QTodoTxt/QTodoTxt2#18]
Should all cols be resizeable? -> If yes, store col sizes.
Should the cols be moveable? -> If yes, store col positions.
Should the user be able to hide/show the cols for counting?

In QTodoTxt1 the width of filterview changes with the width of the mainwindow. Do you/we want this here also?

OT: Are there other things which you want me to implement/repair now?

**Comment by oroulet** [comment]
Yes we should let user resize columns and remember size. I want to limit options, is users do not want to see counts they can simply resize them to very small. I do not care about rezising when windows resizes, let it work as default. 

see the other bug for more work, and then what do you think? What should be done or fixed?

**Comment by fuchsmich** [comment]
Ok.

Maybe its best, if I just open issues for things which should be done.

Am 11.05.2017 um 21:03 schrieb oroulet:

**Comment by oroulet** [comment]
> Maybe its best, if I just open issues for things which should be done.

god idea!

**Comment by fuchsmich** [comment]
Yes, occasionally I'm having my bright moments. ;)

Am 12.05.2017 um 13:41 schrieb oroulet:
