### ISSUE TITLE
use resource (qrc) for all icons

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#21]
This is important to facilitate installation and release a beta

**Comment by fuchsmich** [comment]
we will just keep the one icon theme, right?

**Comment by oroulet** [comment]
We might need two. One dark and one white.. But maybe it is possible to
avoid 2 sets by using system icons. If we have only one set of icons we do
not need the concept of theme. But I do not know how well that works on
other systems than linux. Windows for example. Any input? @pkev

**Comment by fuchsmich** [comment]
Ok, so i will keep in mind, that maybe we need more than one.

**Comment by oroulet** [comment]
done
