### ISSUE TITLE
Show Future Tasks

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt2#27]
Show/Hide future tasks doesn't seem to do anything.  the button changes focus correctly, just no actions.  future tasks stay displayed.

**Comment by oroulet** [comment]
I just tested with example and it worked...

**Comment by sttrebo** [comment]
strange, i just re-downloaded the latest and tried again.  maybe i'm missing something?  i have my sort option to sort by due date btw.  here is a couple of screenshots, show future enabled and disabled.

[Show Future - disabled.pdf](https://github.com/QTodoTxt/QTodoTxt2/files/1048049/Show.Future.-.disabled.pdf)
[Show Future - enabled.pdf](https://github.com/QTodoTxt/QTodoTxt2/files/1048050/Show.Future.-.enabled.pdf)

**Comment by oroulet** [comment]
future tasks are flagged with 't:' your tasks do not have this keyword . try with  t:2017-12-31

**Comment by sttrebo** [comment]
knew it was something dumb on my end, sorry about that.
