### ISSUE TITLE
make leyboard navigation on listView work

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#3]
I tried but did not manage ;-). Looks like the focus moves all the time between items and listview and did not manage to control it...
@fuchsmich I let you have a look ;-)

**Comment by oroulet** [comment]
key navigation works until one edit  a task. Then key events are nto sent anymore...

**Comment by oroulet** [comment]
looking further at it it seems to be an issue when pressing escape...

**Comment by fuchsmich** [comment]
Does it work for you now?

**Comment by oroulet** [comment]
yes. closing
