### ISSUE TITLE
completion popup broken

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#31]
the popup appear on the complete left side of app and I get following error message:
file:///home/olivier/dev/qml-qtodotxt/qtodotxt2/qml/CompletionPopup.qml:88: TypeError: Property 'callLater' of object [object Object] is not a function

Looks like this is because I have 5.7.... Is this methods necessary? upgrading qt is a pain in the ass...

**Comment by fuchsmich** [comment]
No, it's not really necessary. It just prevents that setPosition gets called 
multiple times. 
I was sure, I  had checked that callLater ist available in Qt 5.6, but they 
must have changed the documentation meanwhile.... ;)
