### ISSUE TITLE
priority

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt2#34]
when creating a new task, typing the ( brings up the priority dialog (like due: and t: does).  except the priority one does not respond to mouse input.  to select the priorities, have to use the arrow keys on the keyboard.  plus it would be nice if it could add a single space after the closing ).

**Comment by fuchsmich** [comment]
Ok, I will take a look at this.

Am Dienstag 6. Juni 2017 schrieb sttrebo:
> when creating a new task, typing the ( brings up the priority dialog (like due: and t: does).  except the priority one does not respond to mouse input.  to select the priorities, have to use the arrow keys on the keyboard.  plus it would be nice if it could add a single space after the closing ).
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/QTodoTxt/QTodoTxt2/issues/3

-- 
Gesendet von meinem Jolla

**Comment by fuchsmich** [comment]
Both mouse and space after selection should work now.
