### ISSUE TITLE
Python crash - Complete (w/recurrance)

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt2#37]
i think the recurrance function got messed up in latest code.  when i select 'Complete Task' icon on a regular task everything works fine.  when i do this on an item that has 'rec:+1w' I get a 'python has stopped working'...

**Comment by oroulet** [comment]
works fine here... do you have any stack trace in terminal?

**Comment by sttrebo** [comment]
here you go.  looks like it's a problem with the '+' modifier?

task:
(A) 4 Blocker for Scott +Deliverus @Work due:2017-06-07 rec:+1w

trace:
C:\Users\STreboti\My Apps\QTodoTxt2\bin>qtodotxt.py
Traceback (most recent call last):
  File "C:\Users\STreboti\My Apps\QTodoTxt2\bin\..\qtodotxt2\main_controller.py"
, line 311, in completeTask
    new_task = tasklib.recurTask(task)
  File "C:\Users\STreboti\My Apps\QTodoTxt2\bin\..\qtodotxt2\lib\tasklib.py", li
ne 403, in recurTask
    new.threshold += delta
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'datetime.timedelt
a'

removed the '+' from the task and all works fine.

**Comment by oroulet** [comment]
works fin with and without + here. Can you show the entire line failing?

**Comment by sttrebo** [comment]
(A) 4 Blocker for Scott +Deliverus @work due:2017-06-07 rec:+1w - this fails
(A) 4 Blocker for Scott +Deliverus @Work due:2017-06-07 rec:1w - this works
(A) 4 Blocker for Scott +Deliverus @work due:2017-06-07 rec:+1m - this fails
(A) 4 Blocker for Scott +Deliverus due:2017-06-07 rec:+1w - this fails
(A) 4 Blocker for Scott due:2017-06-07 rec:+1w - this fails
4 Blocker for Scott +Deliverus @work due:2017-06-07 rec:+1w - this fails

i can try other lines/scenarios.  what do you mean by 'Can you show the entire line failing?'

**Comment by oroulet** [comment]
Thaks that one feils...not the other I tested....

**Comment by oroulet** [comment]
should be fixed now. I forgot a test

**Comment by sttrebo** [comment]
fixed on my end, thanks
