### ISSUE TITLE
huge BUG with data lose!

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#44]
@fuchsmich in current master if I add a new task, then it looks like the text of the new task replaces the text of the next task! as far as I understand there is something in the new tableview index but I could not find out where

**Comment by fuchsmich** [comment]
I'm having a look.

Am 13.06.2017 um 17:45 schrieb oroulet:

**Comment by fuchsmich** [comment]
somehow the text of the correct task *and* the first task is set.
I have no idea how this can happen...

Am 13.06.2017 um 17:45 schrieb oroulet:

**Comment by fuchsmich** [comment]
I guess I found it.

**Comment by oroulet** [comment]
Ok. Where?

**Comment by fuchsmich** [comment]
Its in the taskline. inputAccepted() gets called multiple times. I'm working on a fix.

**Comment by oroulet** [comment]
I might be naive, but can yoy avoid tracking indexes? Can't you keep track of Task object?

**Comment by fuchsmich** [comment]
yes, this made it a lot easier.

**Comment by oroulet** [comment]
So now you have a solution that should work?

**Comment by fuchsmich** [comment]
As far as I see, yes.
There are still some error messages from qml, when creating a new task and then selecting a filter without quitting editing before.

**Comment by oroulet** [comment]
may we could just disable all actions while editing? it is a bit crazy to change filtering while editing ....

**Comment by fuchsmich** [comment]
That's one aproach I'm testing.

**Comment by oroulet** [comment]
You should remove HTML and text variable in that code. Just get them from task

**Comment by fuchsmich** [comment]
in the taskline? why?

**Comment by oroulet** [comment]
Do they help? Having them only increases the chance to make an error by forgetting to update them. And they generate an error sometimes
