### ISSUE TITLE
[solved] ImportError: No module named 'PyQt5.QtQml'

### ISSUE THREAD

**Issue by TRSx80** [QTodoTxt/QTodoTxt2#49]
`Traceback (most recent call last):
  File "./qtodotxt", line 11, in <module>
    from qtodotxt2 import app
  File "/home/TRSx80/Programs/QTodoTxt2-qml/bin/../qtodotxt2/app.py", line 12, in <module>
    from PyQt5.QtQml import QQmlApplicationEngine
ImportError: No module named 'PyQt5.QtQml'
`

???

I think I have all dependencies installed (well, there are no instructions that I could find for QTodoTxt2 only QTodoTxt) so not sure if I am missing something? Some QML something? I see a bunch of Qt/QML packages in Debian, not sure if I need another one of them? Also, I think my PYTHONPATH is correct. So.... ?

**Comment by oroulet** [comment]
It says that qml is not installed. If you find out which qml package are necessary in Debian let us know. We can update readme and Debian script

**Comment by TRSx80** [comment]
I'm pretty new to using Python (and Linux in general). I installed via pip BTW, not deb. I saw some script to generate a deb file, but I didn't do that. Maybe I should have? I thought that pip pulled in needed dependencies, but maybe not ones that Debian would need to pull in?

**Comment by TRSx80** [comment]
Tried running the buildDebPackage.py, got the following:

~/Programs/QTodoTxt2-qml/packaging/Debian$ python buildDebPackage.py
Traceback (most recent call last):
  File "buildDebPackage.py", line 1, in <module>
    import urllib.request
ImportError: No module named request

~/Programs/QTodoTxt2-qml/packaging/Debian$ python3 buildDebPackage.py
Traceback (most recent call last):
  File "buildDebPackage.py", line 115, in <module>
    version=sys.argv[1]
IndexError: list index out of range

~/Programs/QTodoTxt2-qml/packaging/Debian$ python3.5 buildDebPackage.py
Traceback (most recent call last):
  File "buildDebPackage.py", line 115, in <module>
    version=sys.argv[1]
IndexError: list index out of range

I'll try and see if I can figure out which QML package is needed, IIRC I did look before and there were several. Any ideas?

**Comment by TRSx80** [comment]
I got it!

I tried Debian package qml but that wasn't it.

The one that did it was python3-pyqt5.qtquick! Once I installed that, QTTodoTxt opened right up!

Thanks for the help!

I'm super stoked to try out your program, it looks like exactly what I have been looking for for a todo.txt GUI on GNU/Linux!

Cheers! And keep up the good work!

**Comment by oroulet** [comment]
great! do not hesitate to report bug or feature request. I hope we can soon fix all small bugs an release it

**Comment by TRSx80** [comment]
Careful what you say @oroulet, I might just take you up on that! :)
