### ISSUE TITLE
How do i run this?

### ISSUE THREAD

**Issue by kaushiknfs** [QTodoTxt/QTodoTxt2#58]
How do i download and try out qtodotxt 2 in windows , without doing some extensive compile or something?

**Comment by oroulet** [comment]
Not sure... Maybe installing winpython then writing pip install qtodotxt2 works? Let me know if it does then we can update pip package

**Comment by kaushiknfs** [comment]
Thanks, i was able to install is that way.
But post install am unable to run it by calling

>qtodotxt2

it doesnt error or launch or do anything at all basically.

**Comment by kaushiknfs** [comment]
Looks like PyQt5 module was missing, got that after running python main contr... .

after installing PyQt5 launches fine. Thanks!

**Comment by mimmori** [comment]
what about make an exe file?

**Comment by sergeevabc** [comment]
+1 mere Windows user here who is looking for standalone Windows binary ```*.exe``` to launch.

**Comment by sttrebo** [comment]
hi kaushiknfs-
For me to run it from the sources (Win10 machine)
1- download the file:  WinPython 3.5.3.1Qt5-64bit (*) or 32 bit version at (http://winpython.github.io/)
2- I have found it best to install this off of your root (i.e.: c:\winpython). not in program files or apps (doesn't seem to work for me).
3- register it by running winpython control panel.exe.  select 'advanced' then 'register distribution'
4-download QTodoTxt2 source and unzip to a location of your choice.
5- navigate to the 'bin' subdirectory of QTodoTxt2 and run the 'qtodotxt.pyw' file.
6-In QToDoTxt2 open/select you todo file and you should be good to go.

hope this helps.
steve

**Comment by oroulet** [comment]
@sttrebo Thanks for your description. I an copying it in readme

**Comment by sergeevabc** [comment]
There are a few related topics on Stackoverflow advocating to try CXFreeze (tutorials: [3.2][1] and [3.6][2]).

[1]: http://blog.notfaqs.com/2011/09/python-32-create-executable-with.html
[2]: https://regilanj.wordpress.com/2017/06/07/py-to-exe-in-python-3-6-1/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by pedro7** [comment]
It is my understanding QTodoTxT2 has not yet reached the phase where creating an installer is worth the time it will occupy in maintenance.
For now, your best bet is [QTodoTxt version 1](https://github.com/QTodoTxt/QTodoTxt).

**Comment by oroulet** [comment]
Qtodotxt2 works fine. Many users use it. The only reason it does not have a Windows installer is that the main authors do not have a Windows pc available... If someone fixed the setup.py files to generate a Windows installer, i will merge it

**Comment by alvcap** [comment]
https://github.com/QTodoTxt/QTodoTxt2/releases

**Comment by sergeevabc** [comment]
UI is laggy and the app crashes in less than a minute. [Proof][1] (available till 2019-04-15).

[1]: https://linx.li/qphxtd5b.mp4

**Comment by topas-rec** [comment]
@sergeevabc thanks for reporting this. Can you open a new issue? Your issue is not related to this one I think.
I havent't found a similar issue that exists already - so please open a new one. Can you also provide more information about the operating system and environment in general. Hohw did you install QTodoTxt2 and so on.

Thanks.
