### ISSUE TITLE
How to change default save path for txt file? 

### ISSUE THREAD

**Issue by Weej1** [QTodoTxt/QTodoTxt2#66]
Hi! My question is exactly that: how do I change path for todo.txt file? I click on preferences but it does nothing. Any help?

**Comment by oroulet** [comment]
Qtodotxt2 sold remember last path. This is the expected behavior in all
programs I know of

**Comment by Weej1** [comment]
Hi! My apologies, the dialogs weren't showing up because of the QML file version thing (in my other post you'll me changing it from QtQuick 2.7 to QtQuick 2.5) I hadn't changed all the files to 2.5 and so those options went missing. - I'll close this since the issue got fixed.
