### ISSUE TITLE
custom sorting of tasks

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#7]
@fuchsmich actions to sort is a good idea, but I think that for now we can have these actions in a menu ("Sorting" for example) and do not clutter the interface with buttons
And let the html property of a task return the entire task as html, inclusive priority

**Comment by oroulet** [comment]
@fuchsmich  does custom sorting works now? It does not on my computer

**Comment by fuchsmich** [comment]
I just made some Actions for this, nothing else.
IMO the sorting should be done in python. After filtering the tasks insert a funtion, which sorts the tasks. I can try myself, if you want to, because I did this already in my sailfish app.

**Comment by oroulet** [comment]
We can have a look at it later. better to focus om making the ground functionality work and fix  bugs so make a release so we get more feedback and maybe more help

**Comment by oroulet** [comment]
kind og works now. but can ne improved
