### ISSUE TITLE
Installation Linux Mint 18.2

### ISSUE THREAD

**Issue by flusi100** [QTodoTxt/QTodoTxt2#80]
Usually instructions for ubuntu 16.04 work, but this is not the case here.
I got various errors, although I installed the following:
`sudo apt-get install python3-pyqt5 qtdeclarative5-models-plugin python3-pyqt5.qtquick qml-module-qt-labs-settings`
Executing qtxttodo leads to the following error (no window is beeing opened)
`QQmlApplicationEngine failed to load component
file:///opt/QTodoTxt2-master/qtodotxt2/qml/QTodoTxt.qml:51 Type Actions unavailable
file:///opt/QTodoTxt2-master/qtodotxt2/qml/Actions.qml:306 Type FileDialog unavailable
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed`
Executing qtodotxt.pyw leads to
`Traceback (most recent call last):
  File "/opt/QTodoTxt2-master/bin/qtodotxt.pyw", line 28, in <module>
    from qtodotxt2 import app
  File "/opt/QTodoTxt2-master/bin/../qtodotxt2/app.py", line 9, in <module>
    from PyQt5 import QtCore
ImportError: No module named PyQt5`

But python3-pyqt5 is installed.

**Comment by oroulet** [comment]
Looks like an issue with qtquick version. I have ubuntu 17.10 so newer..

**Comment by flusi100** [comment]
This is a duplicate of #82
