### ISSUE TITLE
Support for setting file for archiving done tasks

### ISSUE THREAD

**Issue by gsantner** [QTodoTxt/QTodoTxt2#81]
Hi there,
thanks for working on this project!

As the old version doesn't supported it, I thought suggesting it in the new version: Please add the feature for archiving done tasks (I've seen that/use that e.g. in <https://github.com/zagortenay333/timepp__gnome> and <https://github.com/AnthonyDiGirolamo/todotxt-machine>). There seem to be an option in the Preferences, but it seems to do nothing, also I cannot specify a path/filename where the archive for the todo.txt is.

This means, one can specify apart of the todo file another file, a todo-archive file. When the user deletes a task in the todo file, the task gets removed from the todo file and appended to the todo-archive file. This allows then to keep track of what was done when, but without having outdated and unneeded stuff in the todo-list. Would really appreciate if this would work on qtodotxt too.

I store e.g. `~/NextCloud/todo.txt` and `~/NextCloud/todo.archive.txt`.

**Comment by oroulet** [comment]
I think the function is already implement...
