### ISSUE TITLE
Installation process not working

### ISSUE THREAD

**Issue by flusi100** [QTodoTxt/QTodoTxt2#82]
I have a clean and up to date ubuntu 16.04 running, but the installation process as described is not working.
If I execute bin/qtodotxt.pyw, I get the following error:
`Traceback (most recent call last):
  File "Downloads/QTodoTxt2-master/bin/qtodotxt.pyw", line 28, in <module>
    from qtodotxt2 import app
  File "Downloads/QTodoTxt2-master/bin/../qtodotxt2/app.py", line 9, in <module>
    from PyQt5 import QtCore
ImportError: No module named PyQt5
`
And YES: python3-pyqt5 is installed.

If I execute bin/qtodotxt, I get the following output:
`QQmlApplicationEngine failed to load component
file:///home/martin/Downloads/QTodoTxt2-master/qtodotxt2/qml/QTodoTxt.qml:2 module "QtQuick.Controls" is not installed
file:///home/martin/Downloads/QTodoTxt2-master/qtodotxt2/qml/QTodoTxt.qml:4 module "QtQuick.Dialogs" is not installed
file:///home/martin/Downloads/QTodoTxt2-master/qtodotxt2/qml/QTodoTxt.qml:2 module "QtQuick.Controls" is not installed
file:///home/martin/Downloads/QTodoTxt2-master/qtodotxt2/qml/QTodoTxt.qml:4 module "QtQuick.Dialogs" is not installed

filteredTasks about to change in python
`
No window is beeing opened, and the terminal hangs (even Ctrl+C is not working)

**Comment by avLrrakzA2xRJ4VjIgRk** [comment]
Try installing this: qml-module-qt-labs-folderlistmodel

@oroulet maybe we can add this as a dependency to the readme

**Comment by oroulet** [comment]
Yes if it is necessary then we should add it

**Comment by flusi100** [comment]
Unfortunately qtodotxt2 still is not starting. Seem not to be the only missing dependencies.
This is annoying and prevent interested an novice users from trying this software.

**Comment by erikhe90** [comment]
I needed to install the packages `qml-module-qtquick-controls` and `qml-module-qtquick-dialogs` as well.

**Comment by thomasaiman** [comment]
Linux Mint 18.3 (based on ubuntu 16.04) here. I had a similar issue. Followed the instructions in the readme.md and got...
```
QQmlApplicationEngine failed to load component
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:2 module "QtQuick.Controls" is not installed
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:5 module "QtQuick.Window" is not installed
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:3 module "QtQuick.Layouts" is not installed
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:4 module "QtQuick.Dialogs" is not installed
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:1 module "QtQuick" is not installed
```
so I installed those qml module packages with apt. Then got more errors...
```
QQmlApplicationEngine failed to load component
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/QTodoTxt.qml:51 Type Actions unavailable
file:///home/thomas/QTodoTxt2/qtodotxt2/qml/Actions.qml:306 Type FileDialog unavailable
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed
```
so I installed folderlistmodel too.

So it looks like in total I added
```
qml-module-qtquick-controls
qml-module-qtquick-dialogs
qml-module-qtquick-layouts
qml-module-qtquick-privatewidgets
qml-module-qtquick-window2
qml-module-qtquick2
qml-module-qt-labs-folderlistmodel
```
Some them were automatically added as dependencies of others. They're all in the default Ubuntu Xenial repos. QTodoTxt runs fine now.

We need to trace back and document all these dependencies and update the Ubuntu instructions so it would work on a fresh Ubuntu install.

**Comment by topas-rec** [comment]
I think we'll close this issue since it should be solved.
@flusi100 please reopen the issue if it still persists.
