### ISSUE TITLE
Debian 9 - ImportError: No module named QtQml

### ISSUE THREAD

**Issue by lyndhurst** [QTodoTxt/QTodoTxt2#83]
Hi, I am trying to get this new version to work on Debian 9 with no success.

I installed it via `pip install qtodotxt2 --upgrade --pre` as described on the qtodotext page, but it does not run; there is no launcher, and from the command line, I get:

`Traceback (most recent call last):
  File "/usr/local/bin/qtodotxt2", line 7, in <module>
    from qtodotxt2.app import run
  File "/usr/local/lib/python2.7/dist-packages/qtodotxt2/app.py", line 11, in <module>
    from PyQt5.QtQml import QQmlApplicationEngine
ImportError: No module named QtQml
`

I am aware that a similar issue has been solved #49 , but the solution did not work for me..
according to the user the issue was solved by installing python3-pyqt5.qtquick , in my case, it did not help.

python3-pyqt5  python3-pyqt5.qtquick qml-module-qt-labs-settings , all seem to have installed correctly.

The only one apt cannot locate is qtdeclarative5-models-plugin .

I decided to install this [Ubuntu deb package](https://ubuntu.pkgs.org/17.04/ubuntu-universe-amd64/qtdeclarative5-models-plugin_5.7.1-1ubuntu1~7_amd64.deb.html) , but it did not help.

I found this [page](http://metadata.ftp-master.debian.org/changelogs/main/q/qtdeclarative-opensource-src/unstable_changelog) looking around for a solution, and there, they mention a naming issue: 
> * Rename QML modules as such, creating the proper transitional packages and
>     renaming the necessary files:
>  qtdeclarative5-models-plugin → qml-model-qtqml-models2.

I am afraid, my skills are very limited, and I am not sure all those infos are useful, but
I would be very grateful if you could help me, thank you for your time.

**Comment by budinero** [comment]
Can you try with pip3? (python3-pip)

**Comment by lyndhurst** [comment]
Thank you for replying. It did solve it.
Thanks.
