### ISSUE TITLE
require python3 in qtodotxt.pyw?

### ISSUE THREAD

**Issue by thomasaiman** [QTodoTxt/QTodoTxt2#89]
/bin/qtodotxt.pyw begins with `#!/usr/bin/env python` instead of `#!/usr/bin/env python3`

This gave me problems because the readme currently directs the user to install the required Qt packages for python3 (not python2, which is usually the system default)

**Comment by oroulet** [comment]
Can't you send pr?

**Comment by oroulet** [comment]
done
