### ISSUE TITLE
Filters not sorting tasks properly on Manjaro XFCE

### ISSUE THREAD

**Issue by lamalediction** [QTodoTxt/QTodoTxt2#98]
Hello,
This is probably mostly caused by my config (or my ignorance...) but someone might be able to help me out so here goes: 
I'm on Manjaro (with XFCE) and I'm pretty sure I have all the necessary packages (but maybe not the right versions as some are used by the system and I can't update them...).
Qtodotxt2 seems to work alright until I click on a filter, when I do that, some tasks are indeed filtered out but it's seems random.

Here's what I get when I launch Qtodotxt2 in the console:

$ qtodotxt2 
qt5ct: using qt5ct plugin
filteredTasks about to change in python
qml: TableViewSelection: index out of range
inotify_add_watch("/mnt/data/Nextcloud/Notes/todo.txt") failed: "No space left on device"
filteredTasks about to change in python
filteredTasks about to change in python
inotify_add_watch("/home/lamalediction/.config/qt5ct") failed: "No space left on device"
inotify_add_watch("/mnt/data/Nextcloud/Notes/todo.txt") failed: "No space left on device"

**Comment by oroulet** [comment]
looks like your system is broken...no space on disk, then  many funny things might happen...

**Comment by lamalediction** [comment]
Thanks for the pointer!
I've fixed the "no space left on device" by increasing the inotify watch limit but the result is still the same here's what I get in the console now:
$ qtodotxt2 
qt5ct: using qt5ct plugin
filteredTasks about to change in python
qml: TableViewSelection: index out of range
filteredTasks about to change in python

**Comment by dwuttke90** [comment]
same behaviour for me here. filters seem to be random.

also getting the same logs:
qml: TableViewSelection: index out of range
filteredTasks about to change in python

Arch Linux with KDE Plasma

**Comment by alvcap** [comment]
It seems to me that this points to the same issue addressed in #101 and #121.

**Comment by topas-rec** [comment]
Might be.
This issue is old and we have a new version which fixes this or a similar issue.
I'll course this now.
If this issue still persists and the reporter (s) can reconstruct the issue please reopen this issue or comment on it.

**Comment by lamalediction** [comment]
It was the same issue indeed, I can confirm it's now fixed thank you very much!
