### ISSUE TITLE
Packaging / Release

### ISSUE THREAD

**Issue by topas-rec** [QTodoTxt/QTodoTxt2#99]
I recently wanted to create a linux package and found out we don't have something in the archive like a release or tag. This is needed for packaging I think.
Perhaps thats because we don't want to release something because the app is not fit enough to get a release.
Can we / I create an alpha release?

**Comment by oroulet** [comment]
No problem to create a beta.It is usable although some small bugs..

**Comment by topas-rec** [comment]
Created: https://github.com/QTodoTxt/QTodoTxt2/releases/tag/2.0.0
